// Generated by verif/models/palette5242.py from MAME's resistor weights.
// 5-bit channel value -> 8-bit output: normal, shadow (effects bank,
// palette bit 15 clear) and hilight (effects bank, bit 15 set).
localparam [7:0] PAL_NORMAL [0:31] = '{
    8'd0, 8'd8, 8'd16, 8'd25, 8'd33, 8'd41, 8'd49, 8'd58, 8'd66, 8'd74, 8'd82, 8'd91, 8'd99, 8'd107, 8'd115, 8'd123, 8'd132, 8'd140, 8'd148, 8'd156, 8'd164, 8'd173, 8'd181, 8'd189, 8'd197, 8'd206, 8'd214, 8'd222, 8'd230, 8'd239, 8'd247, 8'd255
};
localparam [7:0] PAL_SHADOW [0:31] = '{
    8'd0, 8'd7, 8'd13, 8'd20, 8'd26, 8'd32, 8'd39, 8'd45, 8'd52, 8'd58, 8'd64, 8'd71, 8'd77, 8'd84, 8'd90, 8'd97, 8'd103, 8'd110, 8'd116, 8'd123, 8'd129, 8'd136, 8'd142, 8'd149, 8'd155, 8'd161, 8'd168, 8'd174, 8'd181, 8'd187, 8'd193, 8'd200
};
localparam [7:0] PAL_HILIGHT [0:31] = '{
    8'd55, 8'd62, 8'd68, 8'd74, 8'd81, 8'd87, 8'd94, 8'd100, 8'd106, 8'd113, 8'd119, 8'd126, 8'd132, 8'd139, 8'd145, 8'd152, 8'd158, 8'd165, 8'd171, 8'd178, 8'd184, 8'd191, 8'd197, 8'd203, 8'd210, 8'd216, 8'd223, 8'd229, 8'd235, 8'd242, 8'd248, 8'd255
};
